package ua.com.blaclion.panels;

import org.apache.log4j.Logger;
import ua.com.blaclion.abstract_classes.Fish;
import ua.com.blaclion.abstract_classes.OceanShape;
import ua.com.blaclion.classes.*;
import ua.com.blaclion.frames.MainFrame;

import javax.swing.*;
import java.awt.*;

/**
 * Class that create the ocean, random amount of all objects in the ocean
 * and pass them to the ocean
 */
public class OceanPanel {
    private JPanel mainPanel;
    private JPanel insPanel;
    private Ocean ocean;
    private Logger logger = Logger.getLogger(this.getClass());
    private SafetyList<DrawFish> drawFishes;
    private SafetyList<DrawRock> drawRocks;
    private SafetyList<DrawAlgae> drawAlgaes;
    private SafetyList<MoveFish> moveFishes;
    private int startAmountOfBarriers = 0;
    private PointsCommonContainer pointsContainer;

    public OceanPanel(MainFrame frame, InfoPanel infoPanel) {
        ocean = new Ocean();
        ocean.setMainFrame(frame);

        int amountOfFishes = 10; //new Random(System.currentTimeMillis()).nextInt(10);
        int amountOfRocks = 3; //new Random(System.currentTimeMillis()).nextInt(5);
        int amountOfAlgaes = 8; //new Random(System.currentTimeMillis()).nextInt(10);
        int amountOfPredators = 5; //new Random(System.currentTimeMillis()).nextInt(5);

        pointsContainer = new PointsCommonContainer();
        ocean.setPointContainer(pointsContainer);

        moveFishes = new SafetyList<>();

        drawFishes = new SafetyList<>();
        for (int i = 0; i < amountOfFishes; i++) {
            Fish fish = FishFactory.getNewFish(GoldFish.class);
            drawFishes.add(new DrawFish(fish));
            fish.setDrawFishes(drawFishes);
            fish.setContainer(pointsContainer);
            fish.setExecutor(infoPanel.getExecutor());
            fish.setMoveFishes(moveFishes);
            moveFishes.add(new MoveFish(fish, ocean));
            Fish.increaseAmountOfFishes();
        }

        for (int i = 0; i < amountOfPredators; i++) {
            Fish fish = FishFactory.getNewFish(PredatorFish.class);
            drawFishes.add(new DrawFish(fish));
            fish.setDrawFishes(drawFishes);
            fish.setContainer(pointsContainer);
            fish.setExecutor(infoPanel.getExecutor());
            fish.setMoveFishes(moveFishes);
            moveFishes.add(new MoveFish(fish, ocean));
            Fish.increaseAmountOfPredators();
        }

        drawRocks = new SafetyList<>();
        for (int i = 0; i < amountOfRocks; i++) {
            OceanShape oceanBarrier = BarrierFactory.getNewShape(Rock.class);
            Rock rock = (Rock) oceanBarrier;
            drawRocks.add(new DrawRock(rock));
            rock.setContainer(pointsContainer);
            startAmountOfBarriers++;
        }

        drawAlgaes = new SafetyList<>();
        for (int i = 0; i < amountOfAlgaes; i++) {
            OceanShape oceanBarrier = BarrierFactory.getNewShape(Algae.class);
            Algae algae = (Algae) oceanBarrier;
            drawAlgaes.add(new DrawAlgae(algae));
            algae.setContainer(pointsContainer);
            startAmountOfBarriers++;
        }

        ocean.setDrawFishes(drawFishes);
        ocean.setDrawRocks(drawRocks);
        ocean.setDrawAlgae(drawAlgaes);

        insPanel.setLayout(new GridLayout(1, 1));
        insPanel.add(ocean);
    }

    public Integer getAmountOfBarriers() {
        return startAmountOfBarriers;
    }

    public SafetyList<MoveFish> getMoveFishes() {
        return moveFishes;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        insPanel = new JPanel();
        insPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(insPanel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
